### ISSUE TITLE
Errors running the build:

### ISSUE THREAD

**Issue by BBaysinger** [byavv/angular2-elastic#16]
ERROR in ./src/polyfills.browser.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/Users/bradley/Downloads/angular2-elastic-master/node_modules/awesome-typescript-loader/src/instance.ts:266:72)
    at Object.ensureInstance (/Users/bradley/Downloads/angular2-elastic-master/node_modules/awesome-typescript-loader/src/instance.ts:145:5)
    at compiler (/Users/bradley/Downloads/angular2-elastic-master/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/Users/bradley/Downloads/angular2-elastic-master/node_modules/awesome-typescript-loader/src/index.ts:18:18)

ERROR in ./src/vendor.browser.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/Users/bradley/Downloads/angular2-elastic-master/node_modules/awesome-typescript-loader/src/instance.ts:266:72)
    at Object.ensureInstance (/Users/bradley/Downloads/angular2-elastic-master/node_modules/awesome-typescript-loader/src/instance.ts:145:5)
    at compiler (/Users/bradley/Downloads/angular2-elastic-master/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/Users/bradley/Downloads/angular2-elastic-master/node_modules/awesome-typescript-loader/src/index.ts:18:18)

ERROR in ./src/main.browser.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/Users/bradley/Downloads/angular2-elastic-master/node_modules/awesome-typescript-loader/src/instance.ts:266:72)
    at Object.ensureInstance (/Users/bradley/Downloads/angular2-elastic-master/node_modules/awesome-typescript-loader/src/instance.ts:145:5)
    at compiler (/Users/bradley/Downloads/angular2-elastic-master/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/Users/bradley/Downloads/angular2-elastic-master/node_modules/awesome-typescript-loader/src/index.ts:18:18)

**Comment by cscummings** [comment]
I got this too.
In webpack.config.js I changed loader section:
   /**
     * Loaders
     * Reference: http://webpack.github.io/docs/configuration.html#module-loaders
     * List: http://webpack.github.io/docs/list-of-loaders.html
     * This handles most of the magic responsible for converting modules
     */
    config.module = {
        rules: [
            // Support for .ts files.
            {
                test: /\.ts$/,
                loaders: ['awesome-typescript-loader', 'angular2-template-loader', '@angularclass/hmr-loader'],
                exclude: [/\.(spec|e2e)\.ts$/, /node_modules\/(?!(ng2-.+))/]
            },
            // copy those assets to output
            {
                test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
                loader: 'file?name=fonts/[name].[hash].[ext]?'
            },

            // Support for *.json files.
            { test: /\.json$/, loader: 'json-loader' },

            // all css required in src/app files will be merged in js files
            { test: /\.css$/, loader: 'raw-loader' },
            // support for .html as raw text
            // todo: change the loader to something that adds a hash to images
            { test: /\.html$/, loader: 'raw-loader', exclude: root('src', 'public') }
        ]
    };

Also updated all dependencies to recent version in package.json. Also in elasticsearch.service.ts this._client.ping has changed - commment out the hello: "elasticsearch" and you can at least build it. There are other errors but at least this will get the code built.
Hope this helps
